# Copyright 2024 Jithun Methusahan
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License

# debug_test.py
import os
import sys

# 1. THE MAGIC FIX: Tell Python to look one folder up BEFORE importing server
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# 2. NOW we can safely import from the root folder
from server import refine_output
from wiki_fetcher import get_raw_wiki
import tiktoken

# 3. SET YOUR KEY

# ... (The rest of your run_benchmark code goes here) ...
os.environ["OPENROUTER_API_KEY"] = "sk-or......"

# 2. IMPORT ONLY WHAT EXISTS NOW
try:
    from server import refine_output
    print("--- SERVER IMPORT SUCCESSFUL ---")
except ImportError as e:
    print(f"--- SERVER IMPORT FAILED: {e} ---")
    exit()

# 3. SIMULATE MESSY OUTPUT FROM ANOTHER MCP (e.g., a Google Search or Slack Dump)
messy_mcp_output = """
[SYSTEM LOG: 2024-05-20T10:00:00Z]
User_Admin: Hello team, I've updated the credentials for the database.
Bot_Assistant: Thank you for the update! Beep Boop.
User_Dev1: What is the new port?
User_Admin: The new port is 5432, and the host is 'db.production.internal'.
User_Dev2: Is the password the same as last month?
User_Admin: No, the new password follows the pattern 'Prod2024!'.
[FOOTER: Confidential information. Auto-generated by Slack-MCP-Server. Page 1 of 500.]
"""

print("--- TESTING PURE REFINER LOGIC ---")
# We tell the refiner to focus ONLY on the database credentials
result = refine_output(messy_mcp_output, "Extract all database credentials mentioned.")

print("\nREFINED SIGNAL FROM MIDDLEMAN:")
print(result)